### ISSUE TITLE
Linechart triggering JS error when combined with responsive container

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts-react#105]
## Expected Behavior

No errors in console

## Current Behavior

The line chart hover triggers errors in the console

## Steps to Reproduce (for bugs)

1. Add Responsive container to linechart demos
2. Hover over it
3. See error in console

<img width="1680" alt="fullscreen_1_11_18__5_27_pm" src="https://user-images.githubusercontent.com/9063187/34855536-0bfe7500-f6f5-11e7-9dd1-0f48e9d80ace.png">

## Your Environment

* Browser Name and version: Chrome

**Comment by davegomez** [comment]
I got the same error and display when changed the `topicLabel` value from `"topics"` to something else in the `<Line />` component prop.

**Comment by davegomez** [comment]
@Golodhros can you check if this issue still exist in the new version? I think this might be solved with the changes to the way we are binding the references.

**Comment by Golodhros** [comment]
Yeah, just added it to my list!

**Comment by miglesiasEB** [comment]
This is working properly too! 
🎉
