### ISSUE TITLE
v4.0.0 is not aligned with Demo

### ISSUE THREAD

**Issue by fireworks2005** [eventbrite/britecharts-react#127]
I have observed that the demo shown in the web page [https://eventbrite.github.io/britecharts-react/#donut](url) uses the ResponsiveContainer to resize the chart according to different viewport. 

However, such feature is not yet available in v4.0.0 lib.  

When likely will be the next release to accommodate the latest codes ?

**Comment by Golodhros** [comment]
Hi @fireworks2005 , thanks for creating this issue!

The Responsive Container is a helper component we use to demo this capability, but we weren't planning to add it to the library as it is out of the scope of it.
That said, you can grab it here: https://github.com/eventbrite/britecharts-react/blob/master/src/charts/helpers/responsiveContainer.js and use it in your projects.

Thanks,

**Comment by fireworks2005** [comment]
Got it. Thanks
