### ISSUE TITLE
Cant set tooltip title to empty string

### ISSUE THREAD

**Issue by karlAlnebratt** [eventbrite/britecharts-react#132]
When using the `<Tooltip />` chart. It is not possible to set an empty title

## Expected Behavior
When I set the Tooltip with an empty title `<Tooltip title="" />` the tooltip should not render a "tooltip title"

## Current Behavior
The tooltip is set to the default title "Tooltip title" instead of only the `formattedDate `

## Possible Solution
The `setChartProperty ` in `src/charts/helpers/configuration.js` do a `false` check for `configuration[key]`, this will not allow setting empty sting hence they evaluate as falsy

## Steps to Reproduce (for bugs)

1. Create a `Chart` with a `Tooltip`
2. Set the tooltip title to an empty string
3. Render the Chart with Tooltip
4.

![screen shot 2018-04-04 at 11 01 48](https://user-images.githubusercontent.com/1122820/38298464-b2348534-37f7-11e8-876e-5f05d28660f3.png)

## Context
I would like to a accomplice the `Britechart` tooltip API for title
```
<static> title(_x)
Gets or Sets the title of the tooltip (to only show the date, set a blank title)
```
http://eventbrite.github.io/britecharts/module-Tooltip.html#.title__anchor

## Your Environment

* Version used:  0.4.0
* Browser Name and version: Chrome 65.0.3325
* Operating System and version: MacOs 10.13.3

**Comment by Golodhros** [comment]
@karlAlnebratt this is solved now, right?

**Comment by karlAlnebratt** [comment]
Yes. Thanks for merging the PR
