### ISSUE TITLE
Bar Chart Y-axis name value getting truncated to '...'

### ISSUE THREAD

**Issue by alcmacys** [eventbrite/britecharts-react#135]
I am trying to create a horizontal bar chart with multiple categories. Upon loading the data in the specified format, I am seeing issues with the name label on my Y-axis being truncated to '...' instead of showing the full name.

Tried setting the width to a large value but too no avail. I also see in the HTML that is generated that it is not a CSS issue, as the values are coded as '...' in the HTML. 

Is britecharts-react doing something behind the curtains? Also wanted to know if there are options to pass in to style the y-axis labels. 

I tried `yAxisLabelOffset={-200}` and it gives an error.

> Error: Method not supported by Britechart: yAxisLabelOffset

## Expected Behavior
Show full name of label value.

## Current Behavior
Truncate label as "xxx ..." or the entire name label as "..."

## Steps to Reproduce (for bugs)

1. Data

```
        "errorBarChart": [
            {
                "value": 0,
                "name": "Undefined"
            },
            {
                "value": 0,
                "name": "AssertionError"
            },
            {
                "value": 14,
                "name": "IllegalArgument"
            },
            {
                "value": 0,
                "name": "SQL Error"
            },
            {
                "value": 1,
                "name": "NoSuchElementException"
            },
            {
                "value": 0,
                "name": "Error - ENV"
            },
            {
                "value": 0,
                "name": "Expected URL"
            },
            {
                "value": 0,
                "name": "Loading"
            },
            {
                "value": 0,
                "name": "Timeout"
            }
        ]
```

2. JSX

```
            <Paper className={classes.paper}>
              <h2>Bar Charts</h2>
              <Bar
                height={300}
                width={900}
                isHorizontal
                isAnimated
                shouldShowLoadingState={false}
                data={errorBarChart}
                colorSchema={colors.colorSchemas.britecharts}
              />
            </Paper>
```

3. See screenshot for more info

## Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/15879039/46564701-ee77c180-c8bd-11e8-9d15-aa61f99fd0d5.png)
![image](https://user-images.githubusercontent.com/15879039/46564766-6514bf00-c8be-11e8-8be1-6287ca787b0e.png)

![image](https://user-images.githubusercontent.com/15879039/46564839-adcc7800-c8be-11e8-9348-5dad00d5f9e3.png)

## Your Environment

* Version used: ^0.4.1
* Browser Name and version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System and version: MacOS 
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @alcmacys, thanks for open an issue!

Could you try to play with the values of the left margin? 

Let me know how it goes.

**Comment by alcmacys** [comment]
Hi @Golodhros - thanks for responding. For the left margin are you referring to the CSS or there is a method to do that? I also notice that some of the methods available on the generic API such as `'yAxisLabelOffset' `is not working on the `britecharts-react`

**Comment by Golodhros** [comment]
Hi @alcmacys,

No, I mean the `margin` configuration of the chart:

            <Bar
                height={300}
                width={900}
                margin={top: 0, left: 40, right: 0, bottom: 0 }

You have the API here: http://eventbrite.github.io/britecharts/module-Bar.html

**Comment by Golodhros** [comment]
Did this help you with this issue @alcmacys?

**Comment by dupski** [comment]
Hey guys. I am also seeing this issue.

<img width="604" alt="screen shot 2018-12-06 at 4 31 30 pm" src="https://user-images.githubusercontent.com/8173903/49559740-a2f09b00-f974-11e8-826f-50a3d0cffcf4.png">

The `margins` prop does not help. The library is actually rendering "..." in the source.

<img width="459" alt="screen shot 2018-12-06 at 4 35 03 pm" src="https://user-images.githubusercontent.com/8173903/49559859-1c888900-f975-11e8-9783-740a54487a52.png">

Searching for "..." in github has not been helpful :P Any thoughts?

**Comment by dupski** [comment]
It appears to be related to the length of the labels. If I reduce the figures then they render correctly, so there must be a magic auto-truncation going on somewhere in the library based on the label string length

<img width="466" alt="screen shot 2018-12-06 at 5 05 26 pm" src="https://user-images.githubusercontent.com/8173903/49560914-522f7100-f979-11e8-8400-fd725a6d36ab.png">
(also got the colours working :) )

**Comment by dupski** [comment]
Related: https://github.com/eventbrite/britecharts/issues/691 - looks like it is caused by use of the internal wrapTextWithEllipses method. I guess we'll need a new release of the main britecharts module to fix

**Comment by miglesiasEB** [comment]
I see, maybe it was a real issue then.

For the time being, could you try to reproduce this issue in a Codepen? This would allow me to play around to see if there is other solution. You could use https://codepen.io/Britecharts/pen/RQQabr as a jumpstart.

Thanks for your time!!

**Comment by dupski** [comment]
Ah, ok, yeah it only happens when you don't allow sufficient left margin (as mentioned in the ticket I linked).

Repro codepen: https://codepen.io/dupski/pen/PxryBe

As mentioned in the other ticket, it would be nice to have the ability to turn this off (or use CSS), but otherwise setting the margin to a high enough number works.

So @alcmacys , you need to add the `margin` prop to your bar, but **use a bigger number than 40 for the left setting**, e.g.

```jsx
<Bar
    ...
    margin={{top: 0, left: 140, right: 0, bottom: 0 }}
/>
```

I reckon this can be closed @miglesiasEB

**Comment by Golodhros** [comment]
Thanks for your time @dupski!!

Yeah, that's usually the case with Britecharts in general. Maybe you are right and we should allow to not activate the automatic ellipsis, but that would make those labels to get cut. In one way, this behavior makes the issue more explicit (although it doesn't tell you: you should give more left margins!), but I know is not ideal.

I think the totally ideal solution would be to have a helper to do one of the modern ellipsis in the middle, so if the number was '1,000.00', it would become '1...0'. I guess it will be a bit tricky, as everything text related in SVG.

**Comment by dupski** [comment]
No worries @Golodhros - thanks for your work on this library :)

I think in general a more complete Getting Started example would be helpful. At the moment the README and docs site over-simplify some of the examples. It would be good to show an example, complete with its associated data (from a `const`), a good-sized initial `margin` setting, and using a colour palette.

I found I had to hunt around quite a bit just to get a basic graph going.

**Comment by Golodhros** [comment]
Makes sense!

I have a tutorial in a post ready to publish once we launch the v1 of Britecharts-React. I was planning to get there long before now, but life got complicated...

I will to push hard in the following months and get this through!

**Comment by dupski** [comment]
Nice man. Happy to help out where I can, let me know :)

I'm hoping to use this library to power the charts in a new open source CRM product I am building :)

**Comment by Golodhros** [comment]
That is great @dupski!! 
Helping developers like you is the goal of Britecharts, so we are glad of having you helping with it!!
