### ISSUE TITLE
StackedArea chart doesn't render correctly

### ISSUE THREAD

**Issue by davegomez** [eventbrite/britecharts-react#136]
I'm having issues when rendering the StackedArea chart in every browser.

## Expected Behavior
The StackedArea chart should look as the default one in the demo.

## Current Behavior
* It shows a black background for the data representations.
* Shows a black line across the Y axis
* Shows a black line below the X axis

## Steps to Reproduce (for bugs)
This is the code I'm using:
```javascript
import { StackedArea, Tooltip } from 'britecharts-react';

const renderStackedAreaChart = props => <StackedArea width={800} {...props} />;

const StackedAreaChart = ({ data, title }) => (
    <Tooltip
        data={data}
        render={renderStackedAreaChart}
        title={title}
    />
);
```

and this is the data I'm passing to it:

```javascript
const data = [
  { date: '2017-12-12T00:00:00Z', name: 'subscribed', value: 0 },
  { date: '2017-12-12T00:00:00Z', name: 'unsubscribed', value: 0 },
  { date: '2017-12-11T00:00:00Z', name: 'subscribed', value: 1 },
  { date: '2017-12-11T00:00:00Z', name: 'unsubscribed', value: 1 },
  { date: '2017-12-10T00:00:00Z', name: 'subscribed', value: 0 },
  { date: '2017-12-10T00:00:00Z', name: 'unsubscribed', value: 0 },
  { date: '2017-12-09T00:00:00Z', name: 'subscribed', value: 0 },
  { date: '2017-12-09T00:00:00Z', name: 'unsubscribed', value: 0 },
  { date: '2017-12-08T00:00:00Z', name: 'subscribed', value: 0 },
  { date: '2017-12-08T00:00:00Z', name: 'unsubscribed', value: 0 }
];

```

## Screenshots (if appropriate):

<img width="827" alt="stackedarea" src="https://user-images.githubusercontent.com/282903/47532358-1e433500-d87e-11e8-9d62-334a200f97b3.png">

## Your Environment

* Version used: 0.4.1
* Browser Name and version: Chrome, Firefox, Safari (latest by 10/25/2018)
* Operating System and version: macOS High Sierra

**Comment by Golodhros** [comment]
Hi @davegomez, thanks for the question.

I think you just need to add the styling to it. If you are using the CDN links it should be OK by adding:
    		<link href='https://cdn.jsdelivr.net/npm/britecharts-react@0.4.1/dist/britecharts-react.min.css' rel='stylesheet' type='text/css'>

in the header of your page

**Comment by davegomez** [comment]
I'm so toasted that I forgot I did the same with the others...

Thanks @Golodhros
