### ISSUE TITLE
Update Node

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts-react#148]
Update node to the last long term supported version

**Comment by davegomez** [comment]
In my PR to update to React 16 I updated all the dependencies but Node. Maybe there's some additional dependencies to update now after a couple of weeks but update to a newer version of the style guide shouldn't be a problem.

**Comment by Golodhros** [comment]
Oh, true, you also updated Styleguidist. 
I will rename this to be only Node.

Thanks!

**Comment by Golodhros** [comment]
Fixed in #156
