### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by orangewit3** [eventbrite/britecharts-react#165]
Enable labels for stacked bar chart

I wanted to know if the stacked bar chart could have a total count value at the end of the bars similar to the single bar chart component.

![Screen Shot 2019-07-17 at 12 19 35 PM](https://user-images.githubusercontent.com/43012690/61404821-2f5d2780-a88d-11e9-85bb-3cd766c9c3e4.png)
-----------------
![Screen Shot 2019-07-17 at 12 24 01 PM](https://user-images.githubusercontent.com/43012690/61405111-d8a41d80-a88d-11e9-90a4-6396cce9bdc8.png)

Essentially the API should have an enableLabels for stacked bar charts too because it is a very important feature as it saves space and allows for a more readable and clean UI. 

The data I want to display is formatted like [someAttribute] : [subAttribute1 : COUNT] [subAttribute2 : COUNT] and a stacked bar chart is the most appropriate display. However, I want to have a label at the end of the bars that displays the total count to make it more readable along with other tool tips that display information on the sub attributes.

**Comment by Golodhros** [comment]
Hi @orangewit3, thanks for the issue!

It makes sense, we could add this.

Would you mind to add this into the [Britecharts repository](https://github.com/eventbrite/britecharts/issues) instead? We will take care of making it available in Britecharts React once is there.

**Comment by orangewit3** [comment]
Hi @Golodhros,

Thanks for the quick response. I'll add it right away. 

Also another question: I saw that there was another open issue regarding the tooltip not working on the stacked bar chart do you know if that's been resolved yet?

**Comment by Golodhros** [comment]
It doesn't seem to. It is malfunctioning on the demo, sorry!

**Comment by davegomez** [comment]
It is fixed @golodhros, my last two PRs fixed both bugs opened in the issues.

I was wondering why you haven’t released a new version of the library with these fixes? 😂

**Comment by Golodhros** [comment]
Oh, sorry @davegomez!! Will do right now!

**Comment by Golodhros** [comment]
Done!

**Comment by miglesiasEB** [comment]
Closing as it is on Britecharts already.
