### ISSUE TITLE
Registry Britecharts-React in jsdelivr to get CDN link

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts-react#41]
## Expected Behavior

We want to be able to provide CDN links to our users the same way we do in Britecharts

## Possible Solution

Registry Britecharts REact in jsdlvr

**Comment by MartinKolarik** [comment]
You can find the files at https://www.jsdelivr.com/package/npm/britecharts-react ;)

**Comment by Golodhros** [comment]
Oh, Awesome!

Thanks
