### ISSUE TITLE
Create Line Chart

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts-react#44]
## Expected Behavior

Have a line chart as the one in Britecharts

**Comment by nathanbirrell** [comment]
Are you looking for anyone to help out with this? 

I need a line chart for a current project of mine, would be good to help out.

**Comment by Golodhros** [comment]
That would be awesome @nathanbirrell!

Take a look at our [docs](https://eventbrite.github.io/britecharts-react/) and our [Contributing guide](https://github.com/eventbrite/britecharts-react/blob/master/CONTRIBUTING.md) and let us know if you bump into any problem, we are around to help!

**Comment by rubenmoya** [comment]
Ooops, I'm sorry @nathanbirrell, I wasn't aware you were taking care of this :(

**Comment by nathanbirrell** [comment]
Ha! No problem, thanks @rubenmoya 👍

**Comment by robotastic** [comment]
I am trying to figure out how to do a different xAxisFormat so it doesn't just display the day of the month. I can't figure it out through. From the propTypes, it looks like it wants a string. Should that be one of the constants like MINUTE_HOUR?

Happy to add to the documentation once I figure out the proper way to do it.

**Comment by Golodhros** [comment]
Hi @robotastic,

Yeah, you could use one of those or event set a 'custom' one and use `xAxisCustomFormat`.

Check http://eventbrite.github.io/britecharts/module-Line.html#.xAxisFormat__anchor for more details.
