### ISSUE TITLE
Create Bar Chart

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts-react#45]
## Expected Behavior

Have a Bar chart as Britecharts'

**Comment by rubenmoya** [comment]
Hi! I'm finishing the `Bar Chart`, it's working like a charm in the styleguide, now I just need to add the tests, but I'm getting this error when using `.create`: 
```
TypeError: tspan.node(...).getComputedTextLength is not a function
```
rings a bell?

**Comment by Golodhros** [comment]
Hi @rubenmoya, thanks for doing this!!
That's usually related to the text wrapping helper. In Britecharts, that would be coming from the call to wrapTextWithEllipses inside the bar chart.

If you can't figure it out, you could push a branch and we could take a look.

Thanks a lot!

**Comment by rubenmoya** [comment]
I've opened a PR with the changes and the test failing: https://github.com/eventbrite/britecharts-react/pull/65

I haven't been able to figure it out :(
