### ISSUE TITLE
Build system should copy the Britecharts styles into the dist folder

### ISSUE THREAD

**Issue by Golodhros** [eventbrite/britecharts-react#46]
## Expected Behavior

We want the user to use Britecharts' styles, so we will copy them into the dist folder of Britecharts-React

## Current Behavior

Right now, users need to go and fetch those styles into the Britecharts node_modules folder

## Possible Solution

Some kind of task that brings the styles in

## Context

Making Britecharts React easier to work with

**Comment by miglesiasEB** [comment]
We could use  https://github.com/webpack-contrib/copy-webpack-plugin
