### ISSUE TITLE
Demo responsive container not grabbing the right size

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts-react#50]
## Expected Behavior

The containers show up with the right sizes

## Current Behavior

![fullscreen_11_20_17__5_28_pm](https://user-images.githubusercontent.com/9063187/33050196-6b0b24c2-ce18-11e7-8813-5d46aee9989e.png)

**Comment by dalerasrorov-eb** [comment]
https://github.com/eventbrite/britecharts-react/pull/62
