### ISSUE TITLE
RTL languages not supported in legend

### ISSUE THREAD

**Issue by RoeeTencer** [eventbrite/britecharts-react#52]
Request for support of RTL languages

## Expected Behavior
Full support for all languages

## Current Behavior
Not supporting hebrew in legend component 
## Possible Solution
Please add the rtl support:) 

## Your Environment

* Version used: last version.
* Browser Name and version:
* Operating System and version (desktop or mobile): mac OSX El capitan

![image](https://user-images.githubusercontent.com/16492491/33072524-983cea24-cec8-11e7-8bbc-5a4fa9cca162.png)

**Comment by miglesiasEB** [comment]
Hi @RoeeTencer, thanks for the issue!

I see. It kind of makes sense, as it is made with SVG instead of HTML (that has a built-in support for rtl languages).

**Comment by miglesiasEB** [comment]
I have moved this issue to Britecharts: https://github.com/eventbrite/britecharts/issues/465
A codepen reproducing it would be really appreciated.

Closing this.
