### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts-react#68]
## Expected Behavior

We want to have a code of conduct like the one in Britecharts(https://github.com/eventbrite/britecharts/blob/master/.github/CODE_OF_CONDUCT.md)

## Current Behavior

We don't have any

## Possible Solution

Add the same one and a link from the Contributing guide

## Context

We want to make the project friendly for contributors

**Comment by rubenmoya** [comment]
It's the contact email the same as in Britecharts?

**Comment by Golodhros** [comment]
Yeah, that's right. Thanks
