### ISSUE TITLE
Improve charts mock data 

### ISSUE THREAD

**Issue by rubenmoya** [eventbrite/britecharts-react#71]
## Current Behavior
I started working in the `line` chart, and I realised that the `testData` file is getting quite big, and it will be a pain to work with it pretty soon

## Possible Solution
I've thought about having the mock data in the same folder as the chart/component, for example:

```
charts/
├── line/
|   ├── lineChart.js               // chart code
|   ├── lineChart.spec.js          // chart-specific unit tests
|   ├── lineChart.fixtures.js      // any mock data the chart tests / examples might need
|   ├── LineComponent.js           // component-specific code
|   └── LineComponent.spec.js      // component-specific unit tests
```

What do you think?

**Comment by Golodhros** [comment]
That sounds awesome! Go ahead!
