### ISSUE TITLE
Tooltip erroring when using responsive container in line chart

### ISSUE THREAD

**Issue by rubenmoya** [eventbrite/britecharts-react#73]
I've found a problem with the tooltip not being rendered correctly

## Current Behavior
<img width="427" alt="screen shot 2017-12-07 at 13 05 12" src="https://user-images.githubusercontent.com/905225/33714506-764620dc-db4f-11e7-8686-74471b2221d4.png">

I've been trying to debug it and I've found that [here](https://github.com/eventbrite/britecharts/blob/master/src/charts/line.js#L833) `path.nodes()` returns `[]` which later breaks everything with a `Uncaught TypeError: Cannot read property 'getTotalLength' of undefined` in [here](https://github.com/eventbrite/britecharts/blob/master/src/charts/line.js#L902).

## Expected Behavior
It renders the tooltip correctly 

## Steps to Reproduce (for bugs)

1. Checkout the branch used in https://github.com/eventbrite/britecharts-react/pull/72
2. Run the documentation and go to the `multiple lines with tooltip and responsive` example
3. Move the mouse through the chart

**Comment by Golodhros** [comment]
I have checked this and it is a bit puzzling.

The good news is that this error only happens when using the Responsive HOC. It works fine when we render a line chart by itself.

In this PR https://github.com/eventbrite/britecharts-react/pull/85 I have set up Storybook to see this error happening.
