### ISSUE TITLE
Code generator to automate the creation of new chart skeletons

### ISSUE THREAD

**Issue by miglesiasEB** [eventbrite/britecharts-react#81]
## User story
As a contributor, 
I want to run a command to create all the files I need to build a new chart
So that I can get started faster and my experience is great

## Current Behavior
Lots of files to create, and a lot of copy/pasting

## Comments
Check out https://www.npmjs.com/package/plop, it has been used with success in other Eventbrite projects.

## Context
Improving developer experience and reduce maintenance time

**Comment by rubenmoya** [comment]
What do you think it's the minimum skeleton? Just the files? or files plus content? I've realized that most of the charts are the same, just changing some props and the class names.

**Comment by Golodhros** [comment]
I think that with the files, some of the methods and some comments to guide on creating new charts it will be enough.

There won't be a great number of new charts. I was thinking more in streamlining maintenance than in our current creation process, but this will help in both.

**Comment by benmvp** [comment]
I'm really familiar w/ plop, but not familiar with what would be needed in a minimum skeleton. Can you point me to some examples of a couple of charts component examples that you'd wanted auto-generated?

**Comment by miglesiasEB** [comment]
We would love your support on this one @BenAtEventbrite!

A good example of the required structure would be the [bar chart folder][https://github.com/Golodhros/britecharts-react/tree/feat-packages-update/src/charts/bar]. Usually, for a chart called 'foo', we would need:
- Foo.js -> React component
- Foo.test.js -> React component test
- fooChart.fixtures.js -> Testing data
- fooChart.js -> Britecharts-based chart file
- fooChart.test.js -> chart file test
- Readme.md -> Documentation with examples

We would need to add the new chart to the index.js file, but I guess we will need to document that and add it manually.

thanks a lot for your help!!

**Comment by benmvp** [comment]
Sounds simple enough. Is this the index.js file you mean? https://github.com/Golodhros/britecharts-react/blob/feat-packages-update/src/charts/index.js

**Comment by Golodhros** [comment]
Yeah, that one!

**Comment by miglesiasEB** [comment]
Fixed by @speckospock in #112
